// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTTvfPjsC_SrxaFXHsqBuCv6wpVur92Hk',
    appId: '1:740814997239:web:3a6f94d2b750ebd39875f2',
    messagingSenderId: '740814997239',
    projectId: 'face-attendance-geo',
    authDomain: 'face-attendance-geo.firebaseapp.com',
    storageBucket: 'face-attendance-geo.firebasestorage.app',
    measurementId: 'G-6R6JQWT4KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh3-3ivBxYJDZOworEaALrD07yQDz8c10',
    appId: '1:740814997239:android:06585b280b986f849875f2',
    messagingSenderId: '740814997239',
    projectId: 'face-attendance-geo',
    storageBucket: 'face-attendance-geo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqVGyXFI4lVlsxhGhCZST3zXDsHqS5u0c',
    appId: '1:740814997239:ios:9c1579beffabf96f9875f2',
    messagingSenderId: '740814997239',
    projectId: 'face-attendance-geo',
    storageBucket: 'face-attendance-geo.firebasestorage.app',
    iosBundleId: 'com.example.geofenceAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqVGyXFI4lVlsxhGhCZST3zXDsHqS5u0c',
    appId: '1:740814997239:ios:9c1579beffabf96f9875f2',
    messagingSenderId: '740814997239',
    projectId: 'face-attendance-geo',
    storageBucket: 'face-attendance-geo.firebasestorage.app',
    iosBundleId: 'com.example.geofenceAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTTvfPjsC_SrxaFXHsqBuCv6wpVur92Hk',
    appId: '1:740814997239:web:189cfa2006baa6139875f2',
    messagingSenderId: '740814997239',
    projectId: 'face-attendance-geo',
    authDomain: 'face-attendance-geo.firebaseapp.com',
    storageBucket: 'face-attendance-geo.firebasestorage.app',
    measurementId: 'G-66S8V1LDD9',
  );

}